version: '3'

services:
  api:
    container_name: 'smartkidney-api'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USERS_COL
      - DB_BLOODPRESSURE_COL
      - DB_GLOMERULARINFIL_COL
      - DB_BLOODSUGAR_COL
      - API_PORT
    ports:
      - "1323:1323"
  db:
    container_name: 'smartkidney-db'
    image: 'mongo'
    volumes:
      - smartkidney_db:/data/db
    ports:
      - '27077:27017'
  doc:
    image: swaggerapi/swagger-ui
    container_name: "smartkidney-doc"
    ports:
      - "4000:8080"
    environment:
      API_URL: "https://atb-files.s3-ap-southeast-1.amazonaws.com/swagger.json"
volumes:
  smartkidney_db: