version: '3'

services:
  app:
    container_name: 'smartkidney-api'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USERS_COL
      - DB_BLOODPRESSURE_COL
      - DB_GLOMERULARINFIL_COL
      - DB_BLOODSUGAR_COL
      - API_PORT
    ports:
      - "1323:1323"