version: '3'

services:
  api:
    container_name: 'smartkidney-api'
    build:
      context: .
      dockerfile: Dockerfile
    image: smk-api:1
    environment:
      - TZ=Asia/Bangkok
      - DB_HOST
      - DB_NAME
      - DB_USERS_COL
      - DB_BLOODPRESSURE_COL
      - DB_GLOMERULARINFIL_COL
      - DB_BLOODSUGAR_COL
      - DB_BMI_COL
      - DB_WATER_COL
      - API_PORT
    ports:
      - "1323:1323"
    networks: 
      - backend

  db:
    container_name: 'smartkidney-db'
    image: 'mongo'
    volumes:
      - smartkidney_db:/data/db
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '27017:27017'
    networks: 
      - backend

  doc:
    image: swaggerapi/swagger-ui
    container_name: "smartkidney-doc"
    ports:
      - "4040:8080"
    environment:
      API_URL: "https://atb-files.s3-ap-southeast-1.amazonaws.com/swagger.json"
      
volumes:
  smartkidney_db:

networks: 
  backend: